INSERT INTO animatrix.mangalist
(id, idmanga, mangacap, idpag, mangapag) 
VALUES 
('27', 'death_is_the_only_ending_for_the_villainess', '1', '1', 'death_is_the_only_ending_for_the_villainess_cap_1_1.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '2', 'death_is_the_only_ending_for_the_villainess_cap_1_2.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '3', 'death_is_the_only_ending_for_the_villainess_cap_1_3.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '4', 'death_is_the_only_ending_for_the_villainess_cap_1_4.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '5', 'death_is_the_only_ending_for_the_villainess_cap_1_5.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '6', 'death_is_the_only_ending_for_the_villainess_cap_1_6.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '7', 'death_is_the_only_ending_for_the_villainess_cap_1_7.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '1', '8', 'death_is_the_only_ending_for_the_villainess_cap_1_8.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '1', 'death_is_the_only_ending_for_the_villainess_cap_2_1.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '2', 'death_is_the_only_ending_for_the_villainess_cap_2_2.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '3', 'death_is_the_only_ending_for_the_villainess_cap_2_3.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '4', 'death_is_the_only_ending_for_the_villainess_cap_2_4.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '5', 'death_is_the_only_ending_for_the_villainess_cap_2_5.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '6', 'death_is_the_only_ending_for_the_villainess_cap_2_6.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '7', 'death_is_the_only_ending_for_the_villainess_cap_2_7.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '2', '8', 'death_is_the_only_ending_for_the_villainess_cap_2_8.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '1', 'death_is_the_only_ending_for_the_villainess_cap_3_1.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '2', 'death_is_the_only_ending_for_the_villainess_cap_3_2.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '3', 'death_is_the_only_ending_for_the_villainess_cap_3_3.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '4', 'death_is_the_only_ending_for_the_villainess_cap_3_4.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '5', 'death_is_the_only_ending_for_the_villainess_cap_3_5.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '6', 'death_is_the_only_ending_for_the_villainess_cap_3_6.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '7', 'death_is_the_only_ending_for_the_villainess_cap_3_7.jpg'),
('27', 'death_is_the_only_ending_for_the_villainess', '3', '8', 'death_is_the_only_ending_for_the_villainess_cap_3_8.jpg'),